// protobuf_example.h
#include "message.pb.h" // Generated by protoc

class ProtobufHandler : public QObject {
    Q_OBJECT

public:
    explicit ProtobufHandler(QObject *parent = nullptr);

    Q_INVOKABLE void receiveData(const QByteArray &data);

signals:
    void dataReceived(const QString &message);
};
